import { z } from 'zod';
import { Tool, ToolResult } from './types';
import * as fs from 'fs';
import * as path from 'path';

const DocumentGeneratorParams = z.object({
  title: z.string().describe('Report title'),
  content: z.string().describe('Markdown content of the report'),
  filename: z.string().optional().describe('Output filename (default: analysis_report.md)'),
});

async function execute(params: z.infer<typeof DocumentGeneratorParams>): Promise<ToolResult> {
  try {
    const { title, content, filename = 'analysis_report.md' } = params;
    
    // Create reports directory if it doesn't exist
    const reportsDir = path.join(process.cwd(), 'reports');
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }
    
    // Generate full report with header
    const timestamp = new Date().toISOString().split('T')[0];
    const fullReport = `# ${title}

**Generated:** ${timestamp}  
**Agent:** TestIQ - Autonomous CI/CD Test Analyzer

---

${content}

---

*This report was automatically generated by TestIQ.*  
*For questions, contact your DevOps team.*
`;
    
    // Write to file
    const filepath = path.join(reportsDir, filename);
    fs.writeFileSync(filepath, fullReport, 'utf-8');
    
    return {
      success: true,
      data: {
        filepath,
        filename,
        size: fullReport.length,
        message: 'Report generated successfully'
      }
    };
  } catch (error: any) {
    return {
      success: false,
      error: `Failed to generate document: ${error.message}`
    };
  }
}

export const documentGeneratorTool: Tool = {
  name: 'document_generator_tool',
  description: 'Generate a professional Markdown report document. Creates a .md file with the analysis that can be emailed as an attachment. Use this after completing the analysis to create the final report.',
  parameters: DocumentGeneratorParams,
  execute
};